import { useState } from "react";
type Stop={time:string;title:string;note:string;kind?:"museum"|"food"|"sight"|"logistics"};
type Day={id:string;label:string;date:string;title:string;distance:string;transport:string;stops:Stop[]};
const theme={bg:{editor:"#fff"},text:{primary:"#18181b",secondary:"#52525b",tertiary:"#71717a",onAccent:"#fff"},accent:{primary:"#2563eb",control:"#2563eb"},stroke:{primary:"#e4e4e7",secondary:"#d4d4d8"},fill:{tertiary:"#f4f4f5"}};
const days:Day[]=[
{id:"fri",label:"Piątek",date:"4 września",title:"Średniowieczny Tallinn",distance:"7–9 km pieszo",transport:"Lotnisko → Telliskivi: Bolt 15–20 min lub tramwaj T2 do Balti jaam",stops:[
{time:"08:55",title:"Lądowanie w Tallinnie",note:"Czas lokalny jest o godzinę do przodu względem Polski. Dla 4 osób z bagażem najwygodniejszy będzie Bolt.",kind:"logistics"},{time:"10:00",title:"Bagaże i późne śniadanie",note:"Zostawcie bagaże przy Telliskivi 26. Balti Jaama Turg jest kilka minut pieszo i ma dużo szybkich opcji jedzenia.",kind:"food"},{time:"11:15",title:"Toompea i najlepsze panoramy",note:"Patkuli → Kohtuotsa → zamek Toompea z zewnątrz → sobór Aleksandra Newskiego → Ogród Króla Duńskiego.",kind:"sight"},{time:"12:15",title:"Kiek in de Kök i tunele bastionowe",note:"Najlepsze muzeum na połączenie zabytków z historią miasta. Zarezerwujcie około 2 godzin; w tunelach jest 10–12°C.",kind:"museum"},{time:"14:30",title:"Dolne Stare Miasto",note:"Niguliste z zewnątrz → Plac Ratuszowy → Raeapteek → Pasaż św. Katarzyny → brama Viru → ulica Pikk i baszta Gruba Małgorzata.",kind:"sight"},{time:"18:00",title:"Kolacja: Rataskaevu 16",note:"Bardzo popularna restauracja w Starym Mieście. Rezerwacja dla 4 osób jest mocno wskazana.",kind:"food"},{time:"20:15",title:"Fotografiska Night Shift",note:"W piątki muzeum działa do północy. Jest 5 minut od noclegu; opcjonalnie drink na dachu.",kind:"museum"}]},
{id:"sat",label:"Sobota",date:"5 września",title:"Kadriorg, sztuka i nowoczesne centrum",distance:"5–7 km pieszo",transport:"Telliskivi → Kadriorg: tramwaj lub Bolt; powrót przez Rotermann",stops:[{time:"09:00",title:"Śniadanie w okolicy Telliskivi",note:"Zjedzcie blisko noclegu i ruszcie około 09:30.",kind:"food"},{time:"10:00",title:"Kumu Art Museum",note:"Najważniejsze muzeum sztuki Estonii. Zaplanujcie 2–2,5 godziny.",kind:"museum"},{time:"12:45",title:"Pałac i park Kadriorg",note:"Barokowy pałac, ogród kwiatowy, Staw Łabędzi i rezydencja prezydencka z zewnątrz.",kind:"sight"},{time:"14:15",title:"Lunch w Kadriorgu",note:"Wybierzcie spokojną kawiarnię lub restaurację w dzielnicy.",kind:"food"},{time:"15:30",title:"Russalka i nadmorska promenada",note:"Krótki spacer do pomnika Russalka.",kind:"sight"},{time:"17:00",title:"Rotermann Quarter",note:"Dawne zabudowania przemysłowe połączone ze współczesną architekturą.",kind:"sight"},{time:"19:00",title:"Kolacja: RADO",note:"Nowoczesna kuchnia, menu zmieniane codziennie. Koniecznie rezerwacja.",kind:"food"}]},
{id:"sun",label:"Niedziela",date:"6 września",title:"Kalamaja, port i historia morska",distance:"6–8 km pieszo",transport:"Większość dnia pieszo od Telliskivi; Bolt tylko przy mocnym deszczu",stops:[{time:"09:00",title:"Balti Jaama Turg",note:"Śniadanie i szybkie zakupy.",kind:"food"},{time:"10:00",title:"Seaplane Harbour — Lennusadam",note:"Okręt podwodny Lembit, hangary wodnosamolotów i lodołamacz Suur Tõll.",kind:"museum"},{time:"12:45",title:"Patarei i Noblessner",note:"Dawna twierdza-więzienie i odnowiony port Noblessner.",kind:"sight"},{time:"13:30",title:"Lunch: Lore Bistroo",note:"Restauracja w przemysłowym budynku portowym. Rezerwacja wskazana.",kind:"food"},{time:"15:30",title:"Kalamaja i drewniane domy",note:"Spokojny powrót przez uliczki Kalamaja i Telliskivi Creative City.",kind:"sight"},{time:"18:30",title:"Ostatnia kolacja: F-Hoone",note:"Luźna, industrialna restauracja w Telliskivi, blisko noclegu.",kind:"food"},{time:"21:00",title:"Pakowanie i wczesny sen",note:"Na lot o 07:00 zamówcie Bolt około 04:40–04:45.",kind:"logistics"}]}
];
const labels={museum:"Muzeum",food:"Jedzenie",sight:"Zabytek / spacer",logistics:"Logistyka"};
export default function App(){const [selected,setSelected]=useState("fri");const day=days.find(d=>d.id===selected)??days[0];return <main style={{minHeight:"100vh",background:theme.bg.editor,color:theme.text.primary,padding:24,fontFamily:"system-ui,sans-serif"}}><div style={{maxWidth:1100,margin:"0 auto"}}><header style={{paddingBottom:22,borderBottom:`1px solid ${theme.stroke.primary}`}}><div style={{color:theme.accent.primary,fontSize:13,fontWeight:700}}>PLAN DLA 4 OSÓB</div><h1>Tallinn: zabytki, muzea i dobre stoły</h1><p style={{color:theme.text.secondary}}>4–7 września 2026 · baza: Telliskivi tn 26</p></header><section style={{marginTop:28}}><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{days.map(d=><button key={d.id} onClick={()=>setSelected(d.id)} style={{border:`1px solid ${d.id===selected?theme.accent.primary:theme.stroke.primary}`,background:d.id===selected?theme.accent.control:"#fff",color:d.id===selected?"#fff":theme.text.primary,padding:"9px 14px",borderRadius:8,cursor:"pointer",fontWeight:650}}>{d.label} · {d.date}</button>)}</div><div style={{display:"grid",gridTemplateColumns:"240px minmax(0,1fr)",gap:28,marginTop:22}}><aside><h2>{day.title}</h2><p>{day.distance}</p><p style={{color:theme.text.secondary}}>{day.transport}</p></aside><div>{day.stops.map((s,i)=><div key={s.time+s.title} style={{display:"grid",gridTemplateColumns:"66px minmax(0,1fr)",gap:16,paddingBottom:22,borderBottom:i<day.stops.length-1?`1px solid ${theme.stroke.primary}`:"none",marginBottom:18}}><strong>{s.time}</strong><div><h3 style={{margin:0}}>{s.title} <span style={{fontSize:11,fontWeight:400,color:theme.text.tertiary}}>{s.kind?labels[s.kind]:""}</span></h3><p style={{color:theme.text.secondary,lineHeight:1.55}}>{s.note}</p></div></div>)}</div></div></section></div></main>}
